const specialtyToIconMap = {
	Ophthalmology: ["flash-card-icon-1"],
	Optometrist: ["flash-card-icon-1"],
	Gynecology: ["flash-card-icon-2"],
	Obstetrics: ["flash-card-icon-2"],
	"Obstetrics/Gynecology": ["flash-card-icon-2"],
	"Gynecologic Oncology": ["flash-card-icon-2"],
	"Reproductive Endocrinology": ["flash-card-icon-2"],
	Infertility: ["flash-card-icon-2", "flash-card-icon-3"],
	Urology: ["flash-card-icon-3"],
	Nephrology: ["flash-card-icon-3"],
	"Adult Reconstructive Orthopedics": [
		"flash-card-icon-4",
		"flash-card-icon-9",
	],
	"Physical Medicine and Rehabilitation": [
		"flash-card-icon-4",
		"flash-card-icon-9",
		"flash-card-icon-11",
	],
	Rheumatology: ["flash-card-icon-4"],
	"Sports Medicine": ["flash-card-icon-4", "flash-card-icon-9"],
	"Foot and Ankle Orthopedics": ["flash-card-icon-4", "flash-card-icon-9"],
	"Diagnostic Radiology": ["flash-card-icon-5"],
	Radiology: ["flash-card-icon-5"],
	"Interventional Cardiology": ["flash-card-icon-5", "flash-card-icon-14"],
	"Cardiovascular Surgery": ["flash-card-icon-5", "flash-card-icon-14"],
	"Nuclear Medicine": ["flash-card-icon-5", "flash-card-icon-13"],
	"Pulmonary Medicine": ["flash-card-icon-6"],
	"Critical Care": ["flash-card-icon-6"],
	"Internal Medicine": [
		"flash-card-icon-6",
		"flash-card-icon-12",
		"flash-card-icon-13",
		"flash-card-icon-14",
	],
	"Sleep Medicine": ["flash-card-icon-6"],
	"Medical Oncology": ["flash-card-icon-6", "flash-card-icon-10"],
	Psychiatry: ["flash-card-icon-7", "flash-card-icon-11"],
	Neurology: ["flash-card-icon-7", "flash-card-icon-11"],
	"Neurological Surgery": ["flash-card-icon-7", "flash-card-icon-11"],
	Pediatrics: ["flash-card-icon-8"],
	"Family Practice": ["flash-card-icon-8"],
	"General Practice": ["flash-card-icon-8"],
	"Pediatric Cardiology": ["flash-card-icon-8", "flash-card-icon-14"],
	"Pediatric Dermatology": ["flash-card-icon-8"],
	Podiatry: ["flash-card-icon-9"],
	"Hematology/Oncology": ["flash-card-icon-10"],
	"Radiation Oncology": ["flash-card-icon-10"],
	"Surgical Oncology": ["flash-card-icon-10"],
	Hematology: ["flash-card-icon-10"],
	Gastroenterology: ["flash-card-icon-12"],
	"Colon and Rectal Surgery": ["flash-card-icon-12"],
	"Surgery, General": ["flash-card-icon-12"],
	"Endocrinology, Diabetes & Metabolism": ["flash-card-icon-13"],
	Cardiology: ["flash-card-icon-14"],
	"Vascular Surgery": ["flash-card-icon-14"],
};

const iconToBgMap = {
	"flash-card-icon-1": "rgba(107, 161, 180, 1)",
	"flash-card-icon-2": "rgba(195, 98, 96, 1)",
	"flash-card-icon-3": "rgba(72, 72, 170, 1)",
	"flash-card-icon-4": "rgba(150, 65, 80, 1)",
	"flash-card-icon-5": "rgba(65, 111, 137, 1)",
	"flash-card-icon-6": "rgba(136, 72, 102, 1)",
	"flash-card-icon-7": "rgba(176, 195, 60, 1)",
	"flash-card-icon-8": "rgba(27, 74, 110, 1)",
	"flash-card-icon-9": "rgba(27, 74, 110, 1)",
	"flash-card-icon-10": "rgba(141, 35, 70, 1)",
	"flash-card-icon-11": "rgba(145, 43, 58, 1)",
	"flash-card-icon-12": "rgba(115, 41, 30, 1)",
	"flash-card-icon-13": "rgba(132, 22, 72, 1)",
	"flash-card-icon-14": "rgba(121, 27, 45, 1)",
	"flash-card-icon-15": "rgba(255, 172, 186, 1)",
	"flash-card-icon-16": "rgba(165, 143, 255, 1)",
};

export const getSpecialtyIcon = (specialty) => {
	const icons = specialtyToIconMap[specialty] || ["flash-card-icon-16"];
	const icon = icons[Math.floor(Math.random() * icons.length)];
	return { icon, bg: iconToBgMap[icon] };
};
